### ISSUE TITLE
As a xoder I want detailed descriptions for nodes so I can see wiring and usage examples

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#648]
### Rationale

Currently, the only information I can provide to a node is a short tweet-alike piece of text. More detailed info is required to tell what complex nodes do. It could be typical wiring diagrams, usage examples, references, etc.

We should support rich documentation for patches.

### Acceptance criteria

- [x] I can put `README.md` next to `patch.xodp` and see that content included in the node’s documentation on the site rendered below the existing documentation as markdown.
- [x] I can put any assets (PNG, SVG, FZZ) next to `README.md` and they would be available to the documentation renderer. In other words, I can refer local images in my `README.md`
- [x] README and assets survive export/import roundtrip.

### How to implement

Introduce a generic notion of “attachment” for a patch in xodball. That’s a way to store associated files including images and `README.md` itself.

```yaml
patches:
   - id: lalala
   - nodes: [...]
   - links: [...]
   - attachments:
     - filename: README.md
       encoding: utf-8
       content: "foo bar baz readme in markdown with ![images](./smile.png) …"
     - filename: smile.png
       encoding: base64
       content: "c2FkZmRzZnNkZnNkZmRzYWY…"
     - filename: fz.svg
       encoding: utf-8
       content: "<svg viewBox="55 112 894.66211 571.49609"><path d="…" /></svg>"
```

### Out of scope
The same mechanisms seems reasonable to use for implementation files as well to get rid of artificial mapping between names like `cpp` → `any.cpp`
